# Generated by Django 4.2 on 2024-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=15)),
                ("device_info", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("agree_to_participate", models.BooleanField(default=False)),
                ("provided_info", models.BooleanField(default=False)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("occupation", models.TextField(blank=True, null=True)),
                ("dialogue_history", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="business_unit",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="idc",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="businessunit",
            name="parent_unit",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="asset",
        ),
        migrations.AlterUniqueTogether(
            name="disk",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="disk",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="eventlog",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="eventlog",
            name="new_asset",
        ),
        migrations.RemoveField(
            model_name="eventlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="networkdevice",
            name="asset",
        ),
        migrations.AlterUniqueTogether(
            name="nic",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="nic",
            name="asset",
        ),
        migrations.AlterUniqueTogether(
            name="ram",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ram",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="securitydevice",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="server",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="server",
            name="hosted_on",
        ),
        migrations.DeleteModel(
            name="Software",
        ),
        migrations.RemoveField(
            model_name="storagedevice",
            name="asset",
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="BusinessUnit",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="CPU",
        ),
        migrations.DeleteModel(
            name="Disk",
        ),
        migrations.DeleteModel(
            name="EventLog",
        ),
        migrations.DeleteModel(
            name="IDC",
        ),
        migrations.DeleteModel(
            name="Manufacturer",
        ),
        migrations.DeleteModel(
            name="NetworkDevice",
        ),
        migrations.DeleteModel(
            name="NewAssetApprovalZone",
        ),
        migrations.DeleteModel(
            name="NIC",
        ),
        migrations.DeleteModel(
            name="RAM",
        ),
        migrations.DeleteModel(
            name="SecurityDevice",
        ),
        migrations.DeleteModel(
            name="Server",
        ),
        migrations.DeleteModel(
            name="StorageDevice",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
