# Generated by Django 4.2 on 2024-03-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0002_usersession_remove_asset_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="dialogue_history",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
