# Generated by Django 4.2 on 2024-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0003_usersession_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
