# Generated by Django 4.2 on 2024-03-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0004_alter_usersession_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "用户"), ("gpt", "GPT")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogues",
                        to="LLMHPri.usersession",
                    ),
                ),
            ],
        ),
    ]
