# Generated by Django 4.2 on 2024-03-13 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0005_dialogue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="dialogue_history",
        ),
    ]
