# Generated by Django 4.2 on 2024-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0006_remove_usersession_dialogue_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="device_fingerprint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
