# Generated by Django 4.2 on 2024-04-05 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0007_usersession_device_fingerprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="device_fingerprint",
        ),
    ]
