# Generated by Django 4.2 on 2024-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LLMHPri", "0008_remove_usersession_device_fingerprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialogue",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="agree_to_participate",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="device_info",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="provided_info",
        ),
    ]
